### ISSUE TITLE
Gdk-CRITICAL

### ISSUE THREAD

**Issue by dedicate617** [bruvzg/webview_module#2]
when i compiled succeed on ubuntu ,i run the test prj with the follow error:

(godot.x11.tools.32:9571): **Gdk-CRITICAL **: 15:16:47.771: gdk_x11_window_foreign_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed**

how can i fix it,thanks!

**Comment by bruvzg** [comment]
Current Linux/GTK++ code is not finished and non-functional. Fixing it require implementing [xembed](https://www.freedesktop.org/wiki/Specifications/xembed-spec/) protocol.

This module was intended as an experiment only, and there are no plans for future development.
